apiVersion: v1
# Below show a resourcetype to  be Pod  .
kind: Pod
# Metadate section descibe POD Nmae here
metadata:
  name: edgen-container
  labels:
     app: edgen-service-connect
# Spec  specifies rhe  container id to create.
spec:
# Below describes the containers that will run behind  the pod  which includes Container image,name,ports to be used by container. for  now its just 1 container
  containers:
  - image: kshounish/edgen:1
    name: edgen-container
    ports:
    - protocol: TCP
      containerPort: 5000
 

