apiVersion: v1
kind: Service
metadata:
  name: edgen-container-service-replica
  labels:
    app: edgen-container-service-replica
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30001
  selector:
    app: edgen-replica
