apiVersion: v1
kind: Service
metadata:
  name: edgen-container-service
  labels:
    app: edgen-container-service
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30033
  selector:
    app: edgen-service-connect
