CREATE DATABASE web_gen_dev;
GRANT CREATE, CONNECT ON DATABASE web_gen_dev TO postgres;
GRANT CREATE, CONNECT ON DATABASE web_gen_dev TO postgres;
GRANT TEMPORARY ON DATABASE web_gen_dev TO postgres WITH GRANT OPTION;
CONNECT dbname=web_gen_dev user=web_gen password=web_gen123 host=10.0.0.162 port=5432;
CREATE TABLE payment (id serial PRIMARY KEY, orderid integer NOT NULL, paymentmethod VARCHAR(20) NOT NULL, amount integer NOT NULL, _batched_at timestamp without time zone NOT NULL, created DATE NOT NULL);
CREATE TABLE orders (id serial PRIMARY KEY, user_id integer NOT NULL, status VARCHAR(20) NOT NULL, _etl_loaded_at timestamp without time zone NOT NULL, order_date DATE NOT NULL, order_status VARCHAR(255));
CREATE TABLE customers (cid serial PRIMARY KEY, f_name VARCHAR(50), l_name VARCHAR(50));
CREATE DATABASE web_gen_qa;
GRANT CREATE, CONNECT ON DATABASE web_gen_qa TO postgres;
GRANT CREATE, CONNECT ON DATABASE web_gen_qa TO postgres;
GRANT TEMPORARY ON DATABASE web_gen_qa TO postgres WITH GRANT OPTION;
CONNECT dbname=web_gen_qa user=web_gen password=web_gen123 host=10.0.0.162 port=5432;
CREATE TABLE payment (id serial PRIMARY KEY, orderid integer NOT NULL, paymentmethod VARCHAR(20) NOT NULL, amount integer NOT NULL, _batched_at timestamp without time zone NOT NULL, created DATE NOT NULL);
CREATE TABLE orders (id serial PRIMARY KEY, user_id integer NOT NULL, status VARCHAR(20) NOT NULL, _etl_loaded_at timestamp without time zone NOT NULL, order_date DATE NOT NULL, order_status VARCHAR(255));
CREATE TABLE customers (cid serial PRIMARY KEY, f_name VARCHAR(50), l_name VARCHAR(50));
CREATE DATABASE web_gen_perf;
GRANT CREATE, CONNECT ON DATABASE web_gen_perf TO postgres;
GRANT CREATE, CONNECT ON DATABASE web_gen_perf TO postgres;
GRANT TEMPORARY ON DATABASE web_gen_perf TO postgres WITH GRANT OPTION;
CONNECT dbname=web_gen_perf user=web_gen password=web_gen123 host=10.0.0.162 port=5432;
CREATE TABLE payment (id serial PRIMARY KEY, orderid integer NOT NULL, paymentmethod VARCHAR(20) NOT NULL, amount integer NOT NULL, _batched_at timestamp without time zone NOT NULL, created DATE NOT NULL);
CREATE TABLE orders (id serial PRIMARY KEY, user_id integer NOT NULL, status VARCHAR(20) NOT NULL, _etl_loaded_at timestamp without time zone NOT NULL, order_date DATE NOT NULL, order_status VARCHAR(255));
CREATE TABLE customers (cid serial PRIMARY KEY, f_name VARCHAR(50), l_name VARCHAR(50));